package androidx.compose.material3.tokens;

import androidx.compose.ui.text.TextStyle;
import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.text.font.GenericFontFamily;

/* compiled from: go/retraceme 97024faaf470985feb378c0f604e66d2eca678dbbb151206fad2ab4525fd6f86 */
/* loaded from: classes.dex */
public abstract class TypographyTokens {
    public static final TextStyle BodyLarge;
    public static final TextStyle BodyMedium;
    public static final TextStyle BodySmall;
    public static final TextStyle DisplayLarge;
    public static final TextStyle DisplayMedium;
    public static final TextStyle DisplaySmall;
    public static final TextStyle HeadlineLarge;
    public static final TextStyle HeadlineMedium;
    public static final TextStyle HeadlineSmall;
    public static final TextStyle LabelLarge;
    public static final TextStyle LabelMedium;
    public static final TextStyle LabelSmall;
    public static final TextStyle TitleLarge;
    public static final TextStyle TitleMedium;
    public static final TextStyle TitleSmall;

    static {
        TextStyle textStyle = TypographyTokensKt.DefaultTextStyle;
        GenericFontFamily genericFontFamily = TypeScaleTokens.BodyLargeFont;
        FontWeight fontWeight = TypeScaleTokens.BodyLargeWeight;
        BodyLarge = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.BodyLargeSize, fontWeight, genericFontFamily, TypeScaleTokens.BodyLargeTracking, TypeScaleTokens.BodyLargeLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily2 = TypeScaleTokens.BodyMediumFont;
        FontWeight fontWeight2 = TypeScaleTokens.BodyMediumWeight;
        BodyMedium = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.BodyMediumSize, fontWeight2, genericFontFamily2, TypeScaleTokens.BodyMediumTracking, TypeScaleTokens.BodyMediumLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily3 = TypeScaleTokens.BodySmallFont;
        FontWeight fontWeight3 = TypeScaleTokens.BodySmallWeight;
        BodySmall = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.BodySmallSize, fontWeight3, genericFontFamily3, TypeScaleTokens.BodySmallTracking, TypeScaleTokens.BodySmallLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily4 = TypeScaleTokens.DisplayLargeFont;
        FontWeight fontWeight4 = TypeScaleTokens.DisplayLargeWeight;
        DisplayLarge = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.DisplayLargeSize, fontWeight4, genericFontFamily4, TypeScaleTokens.DisplayLargeTracking, TypeScaleTokens.DisplayLargeLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily5 = TypeScaleTokens.DisplayMediumFont;
        FontWeight fontWeight5 = TypeScaleTokens.DisplayMediumWeight;
        DisplayMedium = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.DisplayMediumSize, fontWeight5, genericFontFamily5, TypeScaleTokens.DisplayMediumTracking, TypeScaleTokens.DisplayMediumLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily6 = TypeScaleTokens.DisplaySmallFont;
        FontWeight fontWeight6 = TypeScaleTokens.DisplaySmallWeight;
        DisplaySmall = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.DisplaySmallSize, fontWeight6, genericFontFamily6, TypeScaleTokens.DisplaySmallTracking, TypeScaleTokens.DisplaySmallLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily7 = TypeScaleTokens.HeadlineLargeFont;
        FontWeight fontWeight7 = TypeScaleTokens.HeadlineLargeWeight;
        HeadlineLarge = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.HeadlineLargeSize, fontWeight7, genericFontFamily7, TypeScaleTokens.HeadlineLargeTracking, TypeScaleTokens.HeadlineLargeLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily8 = TypeScaleTokens.HeadlineMediumFont;
        FontWeight fontWeight8 = TypeScaleTokens.HeadlineMediumWeight;
        HeadlineMedium = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.HeadlineMediumSize, fontWeight8, genericFontFamily8, TypeScaleTokens.HeadlineMediumTracking, TypeScaleTokens.HeadlineMediumLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily9 = TypeScaleTokens.HeadlineSmallFont;
        FontWeight fontWeight9 = TypeScaleTokens.HeadlineSmallWeight;
        HeadlineSmall = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.HeadlineSmallSize, fontWeight9, genericFontFamily9, TypeScaleTokens.HeadlineSmallTracking, TypeScaleTokens.HeadlineSmallLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily10 = TypeScaleTokens.LabelLargeFont;
        FontWeight fontWeight10 = TypeScaleTokens.LabelLargeWeight;
        LabelLarge = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.LabelLargeSize, fontWeight10, genericFontFamily10, TypeScaleTokens.LabelLargeTracking, TypeScaleTokens.LabelLargeLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily11 = TypeScaleTokens.LabelMediumFont;
        FontWeight fontWeight11 = TypeScaleTokens.LabelMediumWeight;
        LabelMedium = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.LabelMediumSize, fontWeight11, genericFontFamily11, TypeScaleTokens.LabelMediumTracking, TypeScaleTokens.LabelMediumLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily12 = TypeScaleTokens.LabelSmallFont;
        FontWeight fontWeight12 = TypeScaleTokens.LabelSmallWeight;
        LabelSmall = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.LabelSmallSize, fontWeight12, genericFontFamily12, TypeScaleTokens.LabelSmallTracking, TypeScaleTokens.LabelSmallLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily13 = TypeScaleTokens.TitleLargeFont;
        FontWeight fontWeight13 = TypeScaleTokens.TitleLargeWeight;
        TitleLarge = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.TitleLargeSize, fontWeight13, genericFontFamily13, TypeScaleTokens.TitleLargeTracking, TypeScaleTokens.TitleLargeLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily14 = TypeScaleTokens.TitleMediumFont;
        FontWeight fontWeight14 = TypeScaleTokens.TitleMediumWeight;
        TitleMedium = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.TitleMediumSize, fontWeight14, genericFontFamily14, TypeScaleTokens.TitleMediumTracking, TypeScaleTokens.TitleMediumLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily15 = TypeScaleTokens.TitleSmallFont;
        FontWeight fontWeight15 = TypeScaleTokens.TitleSmallWeight;
        TitleSmall = TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.TitleSmallSize, fontWeight15, genericFontFamily15, TypeScaleTokens.TitleSmallTracking, TypeScaleTokens.TitleSmallLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily16 = TypeScaleTokens.BodyLargeEmphasizedFont;
        FontWeight fontWeight16 = TypeScaleTokens.BodyLargeEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.BodyLargeEmphasizedSize, fontWeight16, genericFontFamily16, TypeScaleTokens.BodyLargeEmphasizedTracking, TypeScaleTokens.BodyLargeEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily17 = TypeScaleTokens.BodyMediumEmphasizedFont;
        FontWeight fontWeight17 = TypeScaleTokens.BodyMediumEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle, 0L, TypeScaleTokens.BodyMediumEmphasizedSize, fontWeight17, genericFontFamily17, TypeScaleTokens.BodyMediumEmphasizedTracking, TypeScaleTokens.BodyMediumEmphasizedLineHeight, null, 16645977);
        TextStyle textStyle2 = TypographyTokensKt.DefaultTextStyle;
        GenericFontFamily genericFontFamily18 = TypeScaleTokens.BodySmallEmphasizedFont;
        FontWeight fontWeight18 = TypeScaleTokens.BodySmallEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.BodySmallEmphasizedSize, fontWeight18, genericFontFamily18, TypeScaleTokens.BodySmallEmphasizedTracking, TypeScaleTokens.BodySmallEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily19 = TypeScaleTokens.DisplayLargeEmphasizedFont;
        FontWeight fontWeight19 = TypeScaleTokens.DisplayLargeEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.DisplayLargeEmphasizedSize, fontWeight19, genericFontFamily19, TypeScaleTokens.DisplayLargeEmphasizedTracking, TypeScaleTokens.DisplayLargeEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily20 = TypeScaleTokens.DisplayMediumEmphasizedFont;
        FontWeight fontWeight20 = TypeScaleTokens.DisplayMediumEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.DisplayMediumEmphasizedSize, fontWeight20, genericFontFamily20, TypeScaleTokens.DisplayMediumEmphasizedTracking, TypeScaleTokens.DisplayMediumEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily21 = TypeScaleTokens.DisplaySmallEmphasizedFont;
        FontWeight fontWeight21 = TypeScaleTokens.DisplaySmallEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.DisplaySmallEmphasizedSize, fontWeight21, genericFontFamily21, TypeScaleTokens.DisplaySmallEmphasizedTracking, TypeScaleTokens.DisplaySmallEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily22 = TypeScaleTokens.HeadlineLargeEmphasizedFont;
        FontWeight fontWeight22 = TypeScaleTokens.HeadlineLargeEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.HeadlineLargeEmphasizedSize, fontWeight22, genericFontFamily22, TypeScaleTokens.HeadlineLargeEmphasizedTracking, TypeScaleTokens.HeadlineLargeEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily23 = TypeScaleTokens.HeadlineMediumEmphasizedFont;
        FontWeight fontWeight23 = TypeScaleTokens.HeadlineMediumEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.HeadlineMediumEmphasizedSize, fontWeight23, genericFontFamily23, TypeScaleTokens.HeadlineMediumEmphasizedTracking, TypeScaleTokens.HeadlineMediumEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily24 = TypeScaleTokens.HeadlineSmallEmphasizedFont;
        FontWeight fontWeight24 = TypeScaleTokens.HeadlineSmallEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.HeadlineSmallEmphasizedSize, fontWeight24, genericFontFamily24, TypeScaleTokens.HeadlineSmallEmphasizedTracking, TypeScaleTokens.HeadlineSmallEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily25 = TypeScaleTokens.LabelLargeEmphasizedFont;
        FontWeight fontWeight25 = TypeScaleTokens.LabelLargeEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.LabelLargeEmphasizedSize, fontWeight25, genericFontFamily25, TypeScaleTokens.LabelLargeEmphasizedTracking, TypeScaleTokens.LabelLargeEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily26 = TypeScaleTokens.LabelMediumEmphasizedFont;
        FontWeight fontWeight26 = TypeScaleTokens.LabelMediumEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.LabelMediumEmphasizedSize, fontWeight26, genericFontFamily26, TypeScaleTokens.LabelMediumEmphasizedTracking, TypeScaleTokens.LabelMediumEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily27 = TypeScaleTokens.LabelSmallEmphasizedFont;
        FontWeight fontWeight27 = TypeScaleTokens.LabelSmallEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.LabelSmallEmphasizedSize, fontWeight27, genericFontFamily27, TypeScaleTokens.LabelSmallEmphasizedTracking, TypeScaleTokens.LabelSmallEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily28 = TypeScaleTokens.TitleLargeEmphasizedFont;
        FontWeight fontWeight28 = TypeScaleTokens.TitleLargeEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.TitleLargeEmphasizedSize, fontWeight28, genericFontFamily28, TypeScaleTokens.TitleLargeEmphasizedTracking, TypeScaleTokens.TitleLargeEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily29 = TypeScaleTokens.TitleMediumEmphasizedFont;
        FontWeight fontWeight29 = TypeScaleTokens.TitleMediumEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.TitleMediumEmphasizedSize, fontWeight29, genericFontFamily29, TypeScaleTokens.TitleMediumEmphasizedTracking, TypeScaleTokens.TitleMediumEmphasizedLineHeight, null, 16645977);
        GenericFontFamily genericFontFamily30 = TypeScaleTokens.TitleSmallEmphasizedFont;
        FontWeight fontWeight30 = TypeScaleTokens.TitleSmallEmphasizedWeight;
        TextStyle.m604copyp1EtxEg$default(textStyle2, 0L, TypeScaleTokens.TitleSmallEmphasizedSize, fontWeight30, genericFontFamily30, TypeScaleTokens.TitleSmallEmphasizedTracking, TypeScaleTokens.TitleSmallEmphasizedLineHeight, null, 16645977);
    }
}
