package com.google.android.systemui.power;

import com.android.internal.logging.UiEventLogger;

/* compiled from: go/retraceme 97024faaf470985feb378c0f604e66d2eca678dbbb151206fad2ab4525fd6f86 */
/* loaded from: classes2.dex */
enum BatteryMetricEvent implements UiEventLogger.UiEventEnum {
    BATTERY_DEFENDER_NOTIFICATION(876),
    BATTERY_DEFENDER_BYPASS_LIMIT(877),
    BATTERY_DEFENDER_BYPASS_LIMIT_FOR_TIPS(878),
    DELETE_BATTERY_DEFENDER_NOTIFICATION(1273),
    ADAPTIVE_CHARGING_NOTIFICATION(1274),
    DELETE_ADAPTIVE_CHARGING_NOTIFICATION(1275),
    ADAPTIVE_CHARGING_NOTIFICATION_BYPASS(1346),
    SEND_INCOMPATIBLE_CHARGING_NOTIFICATION(1271),
    DELETE_INCOMPATIBLE_CHARGING_NOTIFICATION(1272),
    SEND_WIRELESS_CHARGING_NOTIFICATION(1614),
    DISMISS_WIRELESS_CHARGING_NOTIFICATION(1615),
    /* JADX INFO: Fake field, exist only in values array */
    DISABLE_WIRELESS_CHARGING_NOTIFICATION(1616),
    /* JADX INFO: Fake field, exist only in values array */
    SEVERE_BATTERY_DIALOG(991),
    /* JADX INFO: Fake field, exist only in values array */
    SEVERE_BATTERY_DIALOG_TURN_ON(992),
    /* JADX INFO: Fake field, exist only in values array */
    SEVERE_BATTERY_DIALOG_CANCEL(993),
    /* JADX INFO: Fake field, exist only in values array */
    SEVERE_BATTERY_DIALOG_DISMISS_EVENT(994),
    SAVER_CONFIRMATION_DIALOG(1347),
    SAVER_CONFIRMATION_DIALOG_TURN_ON(1348),
    SAVER_CONFIRMATION_DIALOG_CANCEL(1349),
    SAVER_CONFIRMATION_DIALOG_SETUP(1350),
    EXTREME_LOW_BATTERY_NOTIFICATION(1351),
    BATTERY_SAVER_ENABLED(1359),
    BATTERY_SAVER_ENABLED_REASON(1360),
    BATTERY_SAVER_DISABLED(1372),
    BATTERY_SAVER_DISABLED_REASON(1373),
    SEND_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1707),
    DISMISS_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1708),
    ENABLE_CHARGE_LIMIT_FEATURE(1709),
    CLICK_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1712),
    CLICK_WIRELESS_CHARGING_NOTIFICATION(1713),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS(1834),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS(1835),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS_CLICK_TURN_ON(1836),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS_CLICK_SWITCH(1837),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS_DISMISS(1838),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS_DISMISS(1839);

    private final int mId;

    BatteryMetricEvent(int i) {
        this.mId = i;
    }

    public final int getId() {
        return this.mId;
    }
}
