package androidx.compose.ui.graphics;

/* compiled from: go/retraceme 97024faaf470985feb378c0f604e66d2eca678dbbb151206fad2ab4525fd6f86 */
/* loaded from: classes.dex */
public abstract class AndroidBlendMode_androidKt {
    /* renamed from: toAndroidBlendMode-s9anfk8, reason: not valid java name */
    public static final android.graphics.BlendMode m333toAndroidBlendModes9anfk8(int i) {
        return BlendMode.m357equalsimpl0(i, 0) ? android.graphics.BlendMode.CLEAR : BlendMode.m357equalsimpl0(i, 1) ? android.graphics.BlendMode.SRC : BlendMode.m357equalsimpl0(i, 2) ? android.graphics.BlendMode.DST : BlendMode.m357equalsimpl0(i, 3) ? android.graphics.BlendMode.SRC_OVER : BlendMode.m357equalsimpl0(i, 4) ? android.graphics.BlendMode.DST_OVER : BlendMode.m357equalsimpl0(i, 5) ? android.graphics.BlendMode.SRC_IN : BlendMode.m357equalsimpl0(i, 6) ? android.graphics.BlendMode.DST_IN : BlendMode.m357equalsimpl0(i, 7) ? android.graphics.BlendMode.SRC_OUT : BlendMode.m357equalsimpl0(i, 8) ? android.graphics.BlendMode.DST_OUT : BlendMode.m357equalsimpl0(i, 9) ? android.graphics.BlendMode.SRC_ATOP : BlendMode.m357equalsimpl0(i, 10) ? android.graphics.BlendMode.DST_ATOP : BlendMode.m357equalsimpl0(i, 11) ? android.graphics.BlendMode.XOR : BlendMode.m357equalsimpl0(i, 12) ? android.graphics.BlendMode.PLUS : BlendMode.m357equalsimpl0(i, 13) ? android.graphics.BlendMode.MODULATE : BlendMode.m357equalsimpl0(i, 14) ? android.graphics.BlendMode.SCREEN : BlendMode.m357equalsimpl0(i, 15) ? android.graphics.BlendMode.OVERLAY : BlendMode.m357equalsimpl0(i, 16) ? android.graphics.BlendMode.DARKEN : BlendMode.m357equalsimpl0(i, 17) ? android.graphics.BlendMode.LIGHTEN : BlendMode.m357equalsimpl0(i, 18) ? android.graphics.BlendMode.COLOR_DODGE : BlendMode.m357equalsimpl0(i, 19) ? android.graphics.BlendMode.COLOR_BURN : BlendMode.m357equalsimpl0(i, 20) ? android.graphics.BlendMode.HARD_LIGHT : BlendMode.m357equalsimpl0(i, 21) ? android.graphics.BlendMode.SOFT_LIGHT : BlendMode.m357equalsimpl0(i, 22) ? android.graphics.BlendMode.DIFFERENCE : BlendMode.m357equalsimpl0(i, 23) ? android.graphics.BlendMode.EXCLUSION : BlendMode.m357equalsimpl0(i, 24) ? android.graphics.BlendMode.MULTIPLY : BlendMode.m357equalsimpl0(i, 25) ? android.graphics.BlendMode.HUE : BlendMode.m357equalsimpl0(i, 26) ? android.graphics.BlendMode.SATURATION : BlendMode.m357equalsimpl0(i, 27) ? android.graphics.BlendMode.COLOR : BlendMode.m357equalsimpl0(i, 28) ? android.graphics.BlendMode.LUMINOSITY : android.graphics.BlendMode.SRC_OVER;
    }
}
