package com.android.systemui.flags;

import com.android.wm.shell.R;
import java.util.Map;

/* compiled from: go/retraceme 97024faaf470985feb378c0f604e66d2eca678dbbb151206fad2ab4525fd6f86 */
/* loaded from: classes.dex */
public final class Flags {
    public static final ReleasedFlag ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS;
    public static final ReleasedFlag AUTO_PIN_CONFIRMATION;
    public static final ReleasedFlag BLUETOOTH_QS_TILE_DIALOG;
    public static final SysPropBooleanFlag BUILDER_EXTRAS_OVERRIDE;
    public static final ResourceBooleanFlag CHARGING_RIPPLE;
    public static final ResourceBooleanFlag COMMUNAL_SERVICE_ENABLED;
    public static final UnreleasedFlag ENABLE_DARK_VIGNETTE_WHEN_FOLDING;
    public static final ReleasedFlag ENABLE_NEW_PRIVACY_DIALOG;
    public static final UnreleasedFlag ENABLE_NOTIFICATIONS_SIMULATE_SLOW_MEASURE;
    public static final UnreleasedFlag ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS;
    public static final ReleasedFlag ENABLE_USI_BATTERY_NOTIFICATIONS;
    public static final ReleasedFlag ENABLE_WALLET_CONTEXTUAL_LOYALTY_CARDS;
    public static final ReleasedFlag FILTER_PROVISIONING_NETWORK_SUBSCRIPTIONS;
    public static final ResourceBooleanFlag FULL_SCREEN_USER_SWITCHER;
    public static final ReleasedFlag INCOMPATIBLE_CHARGING_BATTERY_ICON;
    public static final ReleasedFlag KEYBOARD_BACKLIGHT_INDICATOR;
    public static final ResourceBooleanFlag LOCKSCREEN_CUSTOM_CLOCKS;
    public static final UnreleasedFlag LOCKSCREEN_ENABLE_LANDSCAPE;
    public static final ReleasedFlag LOCK_SCREEN_LONG_PRESS_ENABLED;
    public static final ReleasedFlag MEDIA_RESUME_PROGRESS;
    public static final ReleasedFlag MEDIA_TAP_TO_TRANSFER;
    public static final ResourceBooleanFlag MONET;
    public static final ReleasedFlag MONOCHROMATIC_THEME;
    public static final ReleasedFlag NEW_NETWORK_SLICE_UI;
    public static final ReleasedFlag NEW_SHADE_CARRIER_GROUP_MOBILE_ICONS;
    public static final ReleasedFlag NEW_UNLOCK_SWIPE_ANIMATION;
    public static final ReleasedFlag NOTE_TASKS;
    public static final ResourceBooleanFlag NOTIFICATION_DRAG_TO_CONTENTS;
    public static final UnreleasedFlag NULL_FLAG;
    public static final ReleasedFlag POWER_MENU_LITE;
    public static final ReleasedFlag QS_SECONDARY_DATA_SUB_INFO;
    public static final ResourceBooleanFlag QS_USER_DETAIL_SHORTCUT;
    public static final ReleasedFlag QUICK_TAP_IN_PCC;
    public static final ReleasedFlag ROAMING_INDICATOR_VIA_DISPLAY_INFO;
    public static final ReleasedFlag SCREENSHOT_APP_CLIPS;
    public static final ReleasedFlag SHARE_WIFI_QS_BUTTON;
    public static final ReleasedFlag SHORTCUT_LIST_SEARCH_LAYOUT;
    public static final ReleasedFlag SIGNAL_CALLBACK_DEPRECATION;
    public static final ReleasedFlag SMARTSPACE_SHARED_ELEMENT_TRANSITION_ENABLED;
    public static final ReleasedFlag STEP_CLOCK_ANIMATION;
    public static final ReleasedFlag TRACK_STYLUS_EVER_USED;
    public static final ReleasedFlag WALLPAPER_FULLSCREEN_PREVIEW;
    public static final ReleasedFlag WALLPAPER_PICKER_PAGE_TRANSITIONS;
    public static final ReleasedFlag WALLPAPER_PICKER_PREVIEW_ANIMATION;
    public static final ReleasedFlag WALLPAPER_PICKER_UI_FOR_AIWP;
    public static final SysPropBooleanFlag WM_ALWAYS_ENFORCE_PREDICTIVE_BACK;
    public static final SysPropBooleanFlag WM_BUBBLE_BAR;
    public static final ReleasedFlag WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES;
    public static final SysPropBooleanFlag WM_ENABLE_PREDICTIVE_BACK_ANIM;
    public static final SysPropBooleanFlag WM_ENABLE_SHELL_TRANSITIONS;
    public static final ReleasedFlag ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD;

    static {
        FlagsFactory flagsFactory = FlagsFactory.INSTANCE;
        NULL_FLAG = new UnreleasedFlag("null_flag");
        FlagsFactory.unreleasedFlag$default(6, "notification_pipeline_developer_logging");
        FlagsFactory.unreleasedFlag$default(6, "nssl_debug_lines");
        FlagsFactory.unreleasedFlag$default(6, "nssl_debug_remove_animation");
        NOTIFICATION_DRAG_TO_CONTENTS = FlagsFactory.resourceBooleanFlag$default(R.bool.config_notificationToContents, "notification_drag_to_contents");
        BUILDER_EXTRAS_OVERRIDE = FlagsFactory.sysPropBooleanFlag$default("persist.sysui.notification.builder_extras_override", true);
        NEW_UNLOCK_SWIPE_ANIMATION = FlagsFactory.releasedFlag$default("new_unlock_swipe_animation");
        CHARGING_RIPPLE = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_charging_ripple, "charging_ripple");
        LOCKSCREEN_CUSTOM_CLOCKS = FlagsFactory.resourceBooleanFlag$default(R.bool.config_enableLockScreenCustomClocks, "lockscreen_custom_clocks");
        STEP_CLOCK_ANIMATION = FlagsFactory.releasedFlag$default("step_clock_animation");
        FlagsFactory.unreleasedFlag$default(6, "dozing_migration_1");
        FlagsFactory.unreleasedFlag$default(6, "biometrics_animation_revamp");
        ReleasedFlag releasedFlag = new ReleasedFlag("auto_pin_confirmation", "auto_pin_confirmation");
        Map map = FlagsFactory.flagMap;
        map.put("auto_pin_confirmation", releasedFlag);
        AUTO_PIN_CONFIRMATION = releasedFlag;
        ENABLE_WALLET_CONTEXTUAL_LOYALTY_CARDS = FlagsFactory.releasedFlag$default("enable_wallet_contextual_loyalty_cards");
        WALLPAPER_FULLSCREEN_PREVIEW = FlagsFactory.releasedFlag$default("wallpaper_fullscreen_preview");
        LOCK_SCREEN_LONG_PRESS_ENABLED = FlagsFactory.releasedFlag$default("lock_screen_long_press_enabled");
        FlagsFactory.releasedFlag$default("lazy_inflate_keyguard");
        WALLPAPER_PICKER_UI_FOR_AIWP = FlagsFactory.releasedFlag$default("wallpaper_picker_ui_for_aiwp");
        WALLPAPER_PICKER_PAGE_TRANSITIONS = FlagsFactory.releasedFlag$default("wallpaper_picker_page_transitions");
        FlagsFactory.unreleasedFlag$default(6, "wallpaper_picker_grid_apply_button");
        FlagsFactory.unreleasedFlag$default(6, "keyguard_talkback_fix");
        WALLPAPER_PICKER_PREVIEW_ANIMATION = FlagsFactory.releasedFlag$default("wallpaper_picker_preview_animation");
        POWER_MENU_LITE = FlagsFactory.releasedFlag$default("power_menu_lite");
        SMARTSPACE_SHARED_ELEMENT_TRANSITION_ENABLED = FlagsFactory.releasedFlag$default("smartspace_shared_element_transition_enabled");
        FlagsFactory.releasedFlag$default("hide_smartspace_on_dream_overlay");
        FlagsFactory.releasedFlag$default("show_weather_complication_on_dream_overlay");
        FlagsFactory.resourceBooleanFlag$default(R.bool.flag_conversations, "people_tile");
        QS_USER_DETAIL_SHORTCUT = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_lockscreen_qs_user_detail_shortcut, "qs_user_detail_shortcut");
        FULL_SCREEN_USER_SWITCHER = FlagsFactory.resourceBooleanFlag$default(R.bool.config_enableFullscreenUserSwitcher, "full_screen_user_switcher");
        QS_SECONDARY_DATA_SUB_INFO = FlagsFactory.releasedFlag$default("qs_secondary_data_sub_info");
        FlagsFactory.unreleasedFlag$default(2, "enable_new_qs_edit_mode");
        SIGNAL_CALLBACK_DEPRECATION = FlagsFactory.releasedFlag$default("signal_callback_deprecation");
        NEW_NETWORK_SLICE_UI = FlagsFactory.releasedFlag$default("new_network_slice_ui");
        ROAMING_INDICATOR_VIA_DISPLAY_INFO = FlagsFactory.releasedFlag$default("roaming_indicator_via_display_info");
        FILTER_PROVISIONING_NETWORK_SUBSCRIPTIONS = FlagsFactory.releasedFlag$default("filter_provisioning_network_subscriptions");
        INCOMPATIBLE_CHARGING_BATTERY_ICON = FlagsFactory.releasedFlag$default("incompatible_charging_battery_icon");
        NEW_SHADE_CARRIER_GROUP_MOBILE_ICONS = FlagsFactory.releasedFlag$default("new_shade_carrier_group_mobile_icons");
        MONET = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_monet, "monet");
        FlagsFactory.unreleasedFlag$default(6, "region_sampling");
        FlagsFactory.unreleasedFlag$default(6, "screen_contents_translation");
        MONOCHROMATIC_THEME = FlagsFactory.releasedFlag$default("monochromatic");
        FlagsFactory.unreleasedFlag$default(6, "color_fidelity");
        MEDIA_TAP_TO_TRANSFER = FlagsFactory.releasedFlag$default("media_tap_to_transfer");
        FlagsFactory.unreleasedFlag$default(6, "dream_media_complication");
        FlagsFactory.unreleasedFlag$default(6, "dream_media_tap_to_open");
        FlagsFactory.unreleasedFlag$default(6, "media_retain_sessions");
        MEDIA_RESUME_PROGRESS = FlagsFactory.releasedFlag$default("media_resume_progress");
        FlagsFactory.unreleasedFlag$default(6, "media_retain_recommendations");
        FlagsFactory.unreleasedFlag$default(6, "media_remote_resume");
        FlagsFactory.releasedFlag$default("simulate_dock_through_charging");
        ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS = FlagsFactory.releasedFlag$default("always_show_home_controls_on_dreams");
        WM_ENABLE_SHELL_TRANSITIONS = FlagsFactory.sysPropBooleanFlag$default("persist.wm.debug.shell_transit", true);
        WM_BUBBLE_BAR = FlagsFactory.sysPropBooleanFlag$default("persist.wm.debug.bubble_bar", false);
        ReleasedFlag releasedFlag2 = new ReleasedFlag("enable_screen_record_enterprise_policies", "window_manager");
        map.put("enable_screen_record_enterprise_policies", releasedFlag2);
        WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES = releasedFlag2;
        LOCKSCREEN_ENABLE_LANDSCAPE = new UnreleasedFlag("lockscreen.enable_landscape");
        WM_ENABLE_PREDICTIVE_BACK_ANIM = FlagsFactory.sysPropBooleanFlag$default("persist.wm.debug.predictive_back_anim", true);
        WM_ALWAYS_ENFORCE_PREDICTIVE_BACK = FlagsFactory.sysPropBooleanFlag$default("persist.wm.debug.predictive_back_always_enforce", false);
        SCREENSHOT_APP_CLIPS = FlagsFactory.releasedFlag$default("screenshot_app_clips");
        QUICK_TAP_IN_PCC = FlagsFactory.releasedFlag$default("quick_tap_in_pcc");
        FlagsFactory.unreleasedFlag$default(2, "quick_tap_flow_framework");
        FlagsFactory.releasedFlag$default("clipboard_remote_behavior");
        FlagsFactory.unreleasedFlag$default(2, "clipboard_image_timeout");
        NOTE_TASKS = FlagsFactory.releasedFlag$default("keycode_flag");
        TRACK_STYLUS_EVER_USED = FlagsFactory.releasedFlag$default("track_stylus_ever_used");
        FlagsFactory.releasedFlag$default("enable_stylus_charging_ui");
        ENABLE_USI_BATTERY_NOTIFICATIONS = FlagsFactory.releasedFlag$default("enable_usi_battery_notifications");
        FlagsFactory.releasedFlag$default("enable_stylus_education");
        FlagsFactory.unreleasedFlag$default(6, "warn_on_blocking_binder_transactions");
        FlagsFactory.unreleasedFlag$default(6, "user_tracker_background_callbacks");
        ENABLE_DARK_VIGNETTE_WHEN_FOLDING = new UnreleasedFlag("enable_dark_vignette_when_folding");
        ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS = new UnreleasedFlag("enable_unfold_status_bar_animations");
        ENABLE_NOTIFICATIONS_SIMULATE_SLOW_MEASURE = new UnreleasedFlag("enable_notifications_simulate_slow_measure");
        FlagsFactory.unreleasedFlag$default(6, "exp_flag_release");
        SHORTCUT_LIST_SEARCH_LAYOUT = FlagsFactory.releasedFlag$default("shortcut_list_search_layout");
        KEYBOARD_BACKLIGHT_INDICATOR = FlagsFactory.releasedFlag$default("keyboard_backlight_indicator");
        FlagsFactory.unreleasedFlag$default(6, "split_shade_subpixel_optimization");
        FlagsFactory.releasedFlag$default("use_new_activity_starter");
        ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD = FlagsFactory.releasedFlag$default("zj_285570694_lockscreen_transition_from_aod");
        FlagsFactory.unreleasedFlag$default(6, "enable_lockscreen_wallpaper_dream");
        FlagsFactory.unreleasedFlag$default(6, "bigpicture_notification_lazy_loading");
        ENABLE_NEW_PRIVACY_DIALOG = FlagsFactory.releasedFlag$default("enable_new_privacy_dialog");
        FlagsFactory.unreleasedFlag$default(6, "decouple_remote_input_delegate_and_callback_update");
        FlagsFactory.releasedFlag$default("enable_clock_keyguard_presentation");
        SHARE_WIFI_QS_BUTTON = FlagsFactory.releasedFlag$default("share_wifi_qs_button");
        BLUETOOTH_QS_TILE_DIALOG = FlagsFactory.releasedFlag$default("bluetooth_qs_tile_dialog");
        COMMUNAL_SERVICE_ENABLED = FlagsFactory.resourceBooleanFlag$default(R.bool.config_communalServiceEnabled, "communal_service_enabled");
    }
}
