package com.google.android.material;

import android.R;

/* compiled from: go/retraceme 97024faaf470985feb378c0f604e66d2eca678dbbb151206fad2ab4525fd6f86 */
/* loaded from: classes2.dex */
public abstract class R$styleable {
    public static final int[] BottomSheetBehavior_Layout = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.android.wm.shell.R.attr.backgroundTint, com.android.wm.shell.R.attr.behavior_draggable, com.android.wm.shell.R.attr.behavior_expandedOffset, com.android.wm.shell.R.attr.behavior_fitToContents, com.android.wm.shell.R.attr.behavior_halfExpandedRatio, com.android.wm.shell.R.attr.behavior_hideable, com.android.wm.shell.R.attr.behavior_peekHeight, com.android.wm.shell.R.attr.behavior_saveFlags, com.android.wm.shell.R.attr.behavior_significantVelocityThreshold, com.android.wm.shell.R.attr.behavior_skipCollapsed, com.android.wm.shell.R.attr.gestureInsetBottomIgnored, com.android.wm.shell.R.attr.marginLeftSystemWindowInsets, com.android.wm.shell.R.attr.marginRightSystemWindowInsets, com.android.wm.shell.R.attr.marginTopSystemWindowInsets, com.android.wm.shell.R.attr.paddingBottomSystemWindowInsets, com.android.wm.shell.R.attr.paddingLeftSystemWindowInsets, com.android.wm.shell.R.attr.paddingRightSystemWindowInsets, com.android.wm.shell.R.attr.paddingTopSystemWindowInsets, com.android.wm.shell.R.attr.shapeAppearance, com.android.wm.shell.R.attr.shapeAppearanceOverlay, com.android.wm.shell.R.attr.shouldRemoveExpandedCorners};
    public static final int[] Carousel = {com.android.wm.shell.R.attr.carousel_alignment, com.android.wm.shell.R.attr.carousel_backwardTransition, com.android.wm.shell.R.attr.carousel_emptyViewsBehavior, com.android.wm.shell.R.attr.carousel_firstView, com.android.wm.shell.R.attr.carousel_forwardTransition, com.android.wm.shell.R.attr.carousel_infinite, com.android.wm.shell.R.attr.carousel_nextState, com.android.wm.shell.R.attr.carousel_previousState, com.android.wm.shell.R.attr.carousel_touchUpMode, com.android.wm.shell.R.attr.carousel_touchUp_dampeningFactor, com.android.wm.shell.R.attr.carousel_touchUp_velocityThreshold};
    public static final int[] ExtendedFloatingActionButton_Behavior_Layout = {com.android.wm.shell.R.attr.behavior_autoHide, com.android.wm.shell.R.attr.behavior_autoShrink};
    public static final int[] FloatingActionButton_Behavior_Layout = {com.android.wm.shell.R.attr.behavior_autoHide};
    public static final int[] MaterialAutoCompleteTextView = {R.attr.inputType, R.attr.popupElevation, com.android.wm.shell.R.attr.dropDownBackgroundTint, com.android.wm.shell.R.attr.simpleItemLayout, com.android.wm.shell.R.attr.simpleItemSelectedColor, com.android.wm.shell.R.attr.simpleItemSelectedRippleColor, com.android.wm.shell.R.attr.simpleItems};
    public static final int[] MaterialButton = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.android.wm.shell.R.attr.backgroundTint, com.android.wm.shell.R.attr.backgroundTintMode, com.android.wm.shell.R.attr.cornerRadius, com.android.wm.shell.R.attr.elevation, com.android.wm.shell.R.attr.icon, com.android.wm.shell.R.attr.iconGravity, com.android.wm.shell.R.attr.iconPadding, com.android.wm.shell.R.attr.iconSize, com.android.wm.shell.R.attr.iconTint, com.android.wm.shell.R.attr.iconTintMode, com.android.wm.shell.R.attr.rippleColor, com.android.wm.shell.R.attr.shapeAppearance, com.android.wm.shell.R.attr.shapeAppearanceOverlay, com.android.wm.shell.R.attr.strokeColor, com.android.wm.shell.R.attr.strokeWidth, com.android.wm.shell.R.attr.toggleCheckedStateOnClick};
    public static final int[] MaterialCheckBox = {R.attr.button, com.android.wm.shell.R.attr.buttonCompat, com.android.wm.shell.R.attr.buttonIcon, com.android.wm.shell.R.attr.buttonIconTint, com.android.wm.shell.R.attr.buttonIconTintMode, com.android.wm.shell.R.attr.buttonTint, com.android.wm.shell.R.attr.centerIfNoTextEnabled, com.android.wm.shell.R.attr.checkedState, com.android.wm.shell.R.attr.errorAccessibilityLabel, com.android.wm.shell.R.attr.errorShown, com.android.wm.shell.R.attr.useMaterialThemeColors};
    public static final int[] MaterialRadioButton = {com.android.wm.shell.R.attr.buttonTint, com.android.wm.shell.R.attr.useMaterialThemeColors};
    public static final int[] MaterialShape = {com.android.wm.shell.R.attr.shapeAppearance, com.android.wm.shell.R.attr.shapeAppearanceOverlay};
    public static final int[] MaterialSwitch = {com.android.wm.shell.R.attr.thumbIcon, com.android.wm.shell.R.attr.thumbIconSize, com.android.wm.shell.R.attr.thumbIconTint, com.android.wm.shell.R.attr.thumbIconTintMode, com.android.wm.shell.R.attr.trackDecoration, com.android.wm.shell.R.attr.trackDecorationTint, com.android.wm.shell.R.attr.trackDecorationTintMode};
    public static final int[] MaterialTextAppearance = {R.attr.letterSpacing, R.attr.lineHeight, com.android.wm.shell.R.attr.lineHeight};
    public static final int[] MaterialTextView = {R.attr.textAppearance, R.attr.lineHeight, com.android.wm.shell.R.attr.lineHeight};
    public static final int[] ScrollingViewBehavior_Layout = {com.android.wm.shell.R.attr.behavior_overlapTop};
    public static final int[] ShapeAppearance = {com.android.wm.shell.R.attr.cornerFamily, com.android.wm.shell.R.attr.cornerFamilyBottomLeft, com.android.wm.shell.R.attr.cornerFamilyBottomRight, com.android.wm.shell.R.attr.cornerFamilyTopLeft, com.android.wm.shell.R.attr.cornerFamilyTopRight, com.android.wm.shell.R.attr.cornerSize, com.android.wm.shell.R.attr.cornerSizeBottomLeft, com.android.wm.shell.R.attr.cornerSizeBottomRight, com.android.wm.shell.R.attr.cornerSizeTopLeft, com.android.wm.shell.R.attr.cornerSizeTopRight};
    public static final int[] SideSheetBehavior_Layout = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.android.wm.shell.R.attr.backgroundTint, com.android.wm.shell.R.attr.behavior_draggable, com.android.wm.shell.R.attr.coplanarSiblingViewId, com.android.wm.shell.R.attr.shapeAppearance, com.android.wm.shell.R.attr.shapeAppearanceOverlay};
    public static final int[] ThemeEnforcement = {R.attr.textAppearance, com.android.wm.shell.R.attr.enforceMaterialTheme, com.android.wm.shell.R.attr.enforceTextAppearance};
}
